name: compile static file
run-name: build resource to website branch

on:
    push:
        branches:
            # 确保这是你正在使用的分支名称
            - main

jobs:
    deploy-website:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  # 如果你文档需要 Git 子模块，取消注释下一行
                  # submodules: true

            - name: install pnpm
              uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: 8.5.0

            - name: setting Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm

            - name: build document
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
              run: |-
                  pnpm run docs:build
                  > src/.vuepress/dist/.nojekyll

            - name: deploy document
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  # 这是文档部署到的分支名称
                  branch: website
                  folder: src/.vuepress/dist
